version: "3.9"  
services:
  backend:
    build: ./backend
    container_name: be
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/backend
      - ./backend/node_modules:/backend/node_modules
  frontend:
    build: ./frontend
    container_name: fe
    ports:
      - "8001:8001"
    stdin_open: true
    tty: true
    

