version: "3.9"  
services:
  backend:
    build: ./backend
    container_name: be
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/backend
      - ./backend/node_modules:/backend/node_modules
    

